export interface Recipe {
  slug: string;
  title: string;
  description: string;
  image: string;
  cuisine: string;
  category: string;
  prepTime: string;
  cookTime: string;
  servings: number;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  rating: number;
  calories: number;
  ingredients: string[];
  instructions: string[];
  tips: string[];
}

export const recipes: Recipe[] = [
  {
    slug: 'spaghetti-bolognese',
    title: 'Classic Spaghetti Bolognese',
    description:
      'A rich, slow-simmered meat sauce tossed with al dente spaghetti and finished with Parmesan.',
    image:
      'https://images.pexels.com/photos/31637792/pexels-photo-31637792.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    cuisine: 'Italian',
    category: 'Pasta',
    prepTime: '15 min',
    cookTime: '1 hr 30 min',
    servings: 4,
    difficulty: 'Medium',
    rating: 4.8,
    calories: 620,
    ingredients: [
      '400g spaghetti',
      '500g ground beef',
      '1 large onion, finely diced',
      '2 carrots, finely diced',
      '2 celery stalks, finely diced',
      '3 garlic cloves, minced',
      '400g canned crushed tomatoes',
      '2 tbsp tomato paste',
      '1/2 cup red wine',
      '1 cup beef stock',
      '2 tbsp olive oil',
      '1 tsp dried oregano',
      '1 bay leaf',
      'Freshly grated Parmesan',
      'Salt and black pepper to taste',
    ],
    instructions: [
      'Heat olive oil in a large pot over medium heat. Add onion, carrot, and celery; sauté for 8 minutes until softened.',
      'Add the ground beef, breaking it apart with a spoon. Cook until browned all over, about 6-8 minutes.',
      'Stir in the garlic and tomato paste. Cook for 1 minute until fragrant.',
      'Pour in the red wine and let it reduce by half, scraping up any browned bits.',
      'Add the crushed tomatoes, beef stock, oregano, and bay leaf. Bring to a gentle simmer.',
      'Cover partially and let the sauce simmer on low heat for at least 1 hour, stirring occasionally.',
      'Meanwhile, cook the spaghetti in well-salted boiling water until al dente according to package directions.',
      'Drain the pasta and toss with the sauce. Serve in warm bowls topped with freshly grated Parmesan.',
    ],
    tips: [
      'For deeper flavor, make the sauce a day ahead and refrigerate overnight.',
      'Use a mix of beef and pork for a richer, more complex sauce.',
    ],
  },
  {
    slug: 'chicken-curry',
    title: 'Aromatic Chicken Curry',
    description:
      'Tender chicken simmered in a fragrant blend of spices, coconut milk, and fresh tomatoes.',
    image:
      'https://images.pexels.com/photos/10692534/pexels-photo-10692534.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    cuisine: 'Indian',
    category: 'Main',
    prepTime: '20 min',
    cookTime: '40 min',
    servings: 4,
    difficulty: 'Medium',
    rating: 4.7,
    calories: 540,
    ingredients: [
      '600g boneless chicken thighs, cut into pieces',
      '1 can (400ml) full-fat coconut milk',
      '2 large onions, finely sliced',
      '3 garlic cloves, minced',
      '1 tbsp fresh ginger, grated',
      '2 large tomatoes, chopped',
      '2 tbsp curry powder',
      '1 tsp turmeric',
      '1 tsp ground cumin',
      '1 tsp ground coriander',
      '1/2 tsp chili powder',
      '3 tbsp vegetable oil',
      'Fresh cilantro for garnish',
      'Salt to taste',
    ],
    instructions: [
      'Heat oil in a large deep pan over medium heat. Add onions and cook until deeply golden, about 10 minutes.',
      'Add garlic and ginger; cook for 1 minute until fragrant.',
      'Stir in curry powder, turmeric, cumin, coriander, and chili powder. Toast the spices for 30 seconds.',
      'Add the chopped tomatoes and cook until they break down into a thick paste, about 5 minutes.',
      'Add the chicken pieces and stir to coat in the spice mixture. Cook for 5 minutes until lightly browned.',
      'Pour in the coconut milk and bring to a gentle simmer. Cover and cook for 25 minutes until chicken is tender.',
      'Taste and adjust seasoning. Garnish with fresh cilantro and serve with steamed rice or naan.',
    ],
    tips: [
      'Toast whole spices in a dry pan before grinding for maximum aroma.',
      'For a creamier sauce, add an extra half can of coconut milk.',
    ],
  },
  {
    slug: 'avocado-toast',
    title: 'Poached Egg Avocado Toast',
    description:
      'Creamy smashed avocado on crusty sourdough, crowned with a perfectly poached egg.',
    image:
      'https://images.pexels.com/photos/7936736/pexels-photo-7936736.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    cuisine: 'Modern',
    category: 'Breakfast',
    prepTime: '10 min',
    cookTime: '5 min',
    servings: 2,
    difficulty: 'Easy',
    rating: 4.5,
    calories: 340,
    ingredients: [
      '2 thick slices sourdough bread',
      '1 ripe avocado',
      '2 large eggs',
      '1 tbsp white vinegar',
      '1/2 lemon, juiced',
      'Red pepper flakes',
      'Microgreens or arugula',
      'Flaky sea salt',
      'Freshly cracked black pepper',
      'Olive oil for drizzling',
    ],
    instructions: [
      'Toast the sourdough slices until golden and crisp.',
      'Bring a pot of water to a gentle simmer. Add white vinegar.',
      'Crack each egg into a small bowl, then carefully slip into the simmering water. Poach for 3 minutes for a runny yolk.',
      'While the eggs poach, scoop the avocado into a bowl. Add lemon juice, salt, and pepper. Mash to your desired consistency.',
      'Spread the avocado mixture generously on the toasted bread.',
      'Remove the poached eggs with a slotted spoon, drain on a paper towel, and place on top of the avocado.',
      'Finish with red pepper flakes, microgreens, a drizzle of olive oil, and flaky sea salt.',
    ],
    tips: [
      'Use the freshest eggs possible for the best poaching results.',
      'A swirl in the water before adding the egg helps it wrap into a neat shape.',
    ],
  },
  {
    slug: 'gourmet-beef-burger',
    title: 'Gourmet Beef Burger',
    description:
      'Juicy char-grilled patty with melted cheese, caramelized onions, and a toasted brioche bun.',
    image:
      'https://images.pexels.com/photos/8305726/pexels-photo-8305726.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    cuisine: 'American',
    category: 'Main',
    prepTime: '15 min',
    cookTime: '15 min',
    servings: 4,
    difficulty: 'Easy',
    rating: 4.9,
    calories: 720,
    ingredients: [
      '500g ground beef (80/20)',
      '4 brioche buns',
      '4 slices cheddar cheese',
      '2 large onions, thinly sliced',
      '4 lettuce leaves',
      '1 large tomato, sliced',
      '4 pickle slices',
      '2 tbsp butter',
      '1 tbsp olive oil',
      'Salt and black pepper',
      'Ketchup and mayo',
    ],
    instructions: [
      'Divide the ground beef into 4 equal portions and gently form into patties. Do not overwork the meat.',
      'Season both sides generously with salt and pepper.',
      'Heat olive oil in a skillet over medium-low heat. Add onions and cook slowly for 15 minutes until caramelized and golden.',
      'Heat a grill or cast-iron skillet over high heat. Cook the patties for 4 minutes per side for medium.',
      'Place a slice of cheddar on each patty during the last minute and cover to melt.',
      'Butter the brioche buns and toast cut-side down until golden.',
      'Assemble: bottom bun, lettuce, tomato, patty with cheese, caramelized onions, pickles, sauces, top bun.',
    ],
    tips: [
      'Make a small dimple in the center of each patty to prevent it from puffing up.',
      'Let the patties rest for 2 minutes after cooking to keep the juices in.',
    ],
  },
  {
    slug: 'caesar-salad',
    title: 'Grilled Chicken Caesar Salad',
    description:
      'Crisp romaine, homemade creamy Caesar dressing, crunchy croutons, and warm grilled chicken.',
    image:
      'https://images.pexels.com/photos/19938473/pexels-photo-19938473.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    cuisine: 'American',
    category: 'Salad',
    prepTime: '15 min',
    cookTime: '12 min',
    servings: 4,
    difficulty: 'Easy',
    rating: 4.4,
    calories: 380,
    ingredients: [
      '2 boneless chicken breasts',
      '2 large heads romaine lettuce',
      '1 cup day-old bread, cubed',
      '1/3 cup grated Parmesan',
      '1/4 cup mayonnaise',
      '2 tbsp lemon juice',
      '1 tbsp Dijon mustard',
      '2 garlic cloves, minced',
      '1 tsp Worcestershire sauce',
      '1/2 tsp anchovy paste (optional)',
      '3 tbsp olive oil',
      'Salt and black pepper',
    ],
    instructions: [
      'Season chicken breasts with salt, pepper, and 1 tbsp olive oil. Grill over medium-high heat for 6 minutes per side until cooked through. Rest and slice.',
      'Toss bread cubes with 1 tbsp olive oil and a pinch of salt. Bake at 200°C/400°F for 8 minutes until golden and crisp.',
      'In a small bowl, whisk together mayonnaise, lemon juice, Dijon, garlic, Worcestershire, and anchovy paste to make the dressing.',
      'Chop the romaine into bite-sized pieces and place in a large bowl.',
      'Add the dressing and toss to coat the leaves evenly.',
      'Top with sliced chicken, croutons, and grated Parmesan. Finish with cracked black pepper.',
    ],
    tips: [
      'For a traditional Caesar, use a coddled egg instead of mayonnaise.',
      'Grate the Parmesan fresh from a wedge for the best texture and flavor.',
    ],
  },
  {
    slug: 'margherita-pizza',
    title: 'Margherita Pizza',
    description:
      'A Neapolitan classic with San Marzano tomato sauce, fresh mozzarella, and fragrant basil.',
    image:
      'https://images.pexels.com/photos/31596394/pexels-photo-31596394.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    cuisine: 'Italian',
    category: 'Pizza',
    prepTime: '1 hr',
    cookTime: '12 min',
    servings: 2,
    difficulty: 'Medium',
    rating: 4.8,
    calories: 580,
    ingredients: [
      '250g pizza dough (00 flour)',
      '150g San Marzano tomatoes, crushed',
      '125g fresh mozzarella, torn',
      'Fresh basil leaves',
      '2 tbsp extra virgin olive oil',
      '1 garlic clove, minced',
      '1/2 tsp sea salt',
      'Semolina for dusting',
    ],
    instructions: [
      'Prepare the dough at least 1 hour ahead and let it rest at room temperature.',
      'In a bowl, mix crushed tomatoes with garlic, salt, and 1 tbsp olive oil to make the sauce.',
      'Preheat your oven to its highest setting with a pizza stone inside for at least 45 minutes.',
      'Stretch the dough on a floured surface into a 30cm round. Dust a peel with semolina and transfer the dough.',
      'Spread a thin layer of sauce, leaving a border. Distribute torn mozzarella evenly.',
      'Slide the pizza onto the preheated stone. Bake for 8-10 minutes until the crust is charred and cheese is bubbling.',
      'Remove from oven, drizzle with olive oil, and top with fresh basil leaves. Slice and serve immediately.',
    ],
    tips: [
      'Less is more with toppings for a true Margherita.',
      'If you do not have a pizza stone, use the back of a sheet pan preheated in the oven.',
    ],
  },
  {
    slug: 'fluffy-pancakes',
    title: 'Fluffy Buttermilk Pancakes',
    description:
      'Tall, pillowy pancakes with crisp edges, drenched in maple syrup and melted butter.',
    image:
      'https://images.pexels.com/photos/5317627/pexels-photo-5317627.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    cuisine: 'American',
    category: 'Breakfast',
    prepTime: '10 min',
    cookTime: '15 min',
    servings: 4,
    difficulty: 'Easy',
    rating: 4.6,
    calories: 290,
    ingredients: [
      '250g all-purpose flour',
      '2 tbsp sugar',
      '2 tsp baking powder',
      '1/2 tsp baking soda',
      '1/2 tsp salt',
      '480ml buttermilk',
      '2 large eggs',
      '60g unsalted butter, melted',
      '1 tsp vanilla extract',
      'Butter for cooking',
      'Maple syrup for serving',
    ],
    instructions: [
      'In a large bowl, whisk together flour, sugar, baking powder, baking soda, and salt.',
      'In a separate bowl, whisk the buttermilk, eggs, melted butter, and vanilla.',
      'Pour the wet ingredients into the dry and fold gently until just combined. Do not overmix; small lumps are fine.',
      'Let the batter rest for 5 minutes.',
      'Heat a non-stick skillet over medium-low heat and lightly butter it.',
      'Pour 1/3 cup portions of batter onto the skillet. Cook until bubbles form on the surface and edges look set, about 3 minutes.',
      'Flip and cook for another 2 minutes until golden brown on both sides.',
      'Stack and serve warm with maple syrup and a pat of butter.',
    ],
    tips: [
      'Resting the batter allows the flour to hydrate for fluffier pancakes.',
      'Keep cooked pancakes on a wire rack in a 90°C/200°F oven while you finish the batch.',
    ],
  },
  {
    slug: 'tomato-soup',
    title: 'Creamy Roasted Tomato Soup',
    description:
      'Velvety roasted tomato soup with a touch of cream, perfect with crusty garlic bread.',
    image:
      'https://images.pexels.com/photos/8755958/pexels-photo-8755958.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    cuisine: 'Mediterranean',
    category: 'Soup',
    prepTime: '10 min',
    cookTime: '45 min',
    servings: 4,
    difficulty: 'Easy',
    rating: 4.5,
    calories: 220,
    ingredients: [
      '1.5kg ripe tomatoes, halved',
      '1 large onion, quartered',
      '6 garlic cloves, unpeeled',
      '3 tbsp olive oil',
      '1 cup vegetable stock',
      '1/2 cup heavy cream',
      '1 tsp sugar',
      'Fresh basil leaves',
      'Salt and black pepper',
      'Crusty bread for serving',
    ],
    instructions: [
      'Preheat oven to 200°C/400°F. Place tomatoes, onion, and garlic on a baking sheet.',
      'Drizzle with olive oil and season with salt and pepper. Roast for 35 minutes until tomatoes are softened and charred at the edges.',
      'Squeeze the roasted garlic from its skins. Transfer everything to a blender.',
      'Add vegetable stock and sugar, then blend until completely smooth.',
      'Pour the soup into a pot and bring to a gentle simmer over medium heat.',
      'Stir in the heavy cream and adjust seasoning to taste.',
      'Ladle into bowls, garnish with fresh basil and a drizzle of olive oil. Serve with crusty bread.',
    ],
    tips: [
      'Roasting concentrates the tomato flavor far beyond stovetop cooking.',
      'For a vegan version, swap the cream for coconut milk.',
    ],
  },
  {
    slug: 'grilled-salmon',
    title: 'Grilled Salmon with Quinoa',
    description:
      'Perfectly seared salmon fillet served over fluffy quinoa with a lemon-dill sauce.',
    image:
      'https://images.pexels.com/photos/4663250/pexels-photo-4663250.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    cuisine: 'Mediterranean',
    category: 'Main',
    prepTime: '15 min',
    cookTime: '20 min',
    servings: 4,
    difficulty: 'Medium',
    rating: 4.7,
    calories: 460,
    ingredients: [
      '4 salmon fillets (150g each)',
      '1 cup quinoa',
      '2 cups vegetable stock',
      '200g fresh spinach',
      '2 tbsp olive oil',
      '1 lemon, zested and juiced',
      '3 tbsp Greek yogurt',
      '2 tbsp fresh dill, chopped',
      '2 garlic cloves, minced',
      'Salt and black pepper',
    ],
    instructions: [
      'Rinse quinoa under cold water. Combine with vegetable stock in a pot, bring to a boil, then reduce to a simmer. Cover and cook for 15 minutes.',
      'In a small bowl, mix Greek yogurt, lemon juice, dill, and minced garlic to make the sauce. Set aside.',
      'Pat salmon fillets dry and season with salt, pepper, and lemon zest.',
      'Heat olive oil in a skillet over medium-high heat. Place salmon skin-side down and cook for 4 minutes.',
      'Flip and cook for another 3-4 minutes until the fish is just opaque and flakes easily.',
      'In the last 2 minutes, wilt the spinach in a separate pan with a splash of water.',
      'Plate quinoa, top with spinach, then the salmon. Drizzle with the lemon-dill sauce and serve with lemon wedges.',
    ],
    tips: [
      'Let the salmon come to room temperature before cooking for even searing.',
      'Do not overcook; salmon is best when still slightly pink in the center.',
    ],
  },
  {
    slug: 'chocolate-cake',
    title: 'Decadent Chocolate Layer Cake',
    description:
      'Three layers of moist chocolate cake enveloped in silky chocolate buttercream frosting.',
    image:
      'https://images.pexels.com/photos/10249461/pexels-photo-10249461.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    cuisine: 'French',
    category: 'Dessert',
    prepTime: '30 min',
    cookTime: '35 min',
    servings: 12,
    difficulty: 'Hard',
    rating: 4.9,
    calories: 480,
    ingredients: [
      '300g all-purpose flour',
      '300g sugar',
      '90g unsweetened cocoa powder',
      '2 tsp baking powder',
      '1.5 tsp baking soda',
      '1 tsp salt',
      '2 large eggs',
      '250ml buttermilk',
      '125ml vegetable oil',
      '2 tsp vanilla extract',
      '250ml hot coffee',
      '200g dark chocolate, melted',
      '300g unsalted butter, softened',
      '400g powdered sugar',
    ],
    instructions: [
      'Preheat oven to 175°C/350°F. Grease and line three 20cm round cake pans.',
      'In a large bowl, sift together flour, sugar, cocoa powder, baking powder, baking soda, and salt.',
      'Add eggs, buttermilk, oil, and vanilla. Beat on medium speed for 2 minutes.',
      'Slowly pour in the hot coffee and mix until smooth. The batter will be thin.',
      'Divide evenly among the three pans. Bake for 25-30 minutes until a toothpick comes out clean.',
      'Cool in pans for 10 minutes, then turn out onto wire racks to cool completely.',
      'For the frosting, beat softened butter until creamy. Gradually add powdered sugar and cocoa powder.',
      'Mix in melted dark chocolate and beat until light and fluffy.',
      'Layer the cakes with frosting between each layer, then frost the outside. Decorate as desired.',
    ],
    tips: [
      'Chill the cake layers before frosting to prevent crumbling.',
      'The hot coffee enhances the chocolate flavor without making it taste like coffee.',
    ],
  },
];

export function getRecipeBySlug(slug: string): Recipe | undefined {
  return recipes.find((r) => r.slug === slug);
}
